### ISSUE TITLE
undefined method use_ssl

### ISSUE THREAD

**Issue by opello** [ruby-oembed/ruby-oembed#31]
While trying to use ruby-oembed 0.8.8 with jekyll 0.12.1 and https://gist.github.com/vanto/1455726 (all with ruby 1.8), I had to add `require 'net/https'` to `lib/oembed.rb` to get it to work.
The error I received was:

```
Liquid Exception: undefined method `use_ssl=' for #<Net::HTTP www.flickr.com:80 open=false> in index.html
```

**Comment by metavida** [comment]
I'm going to close this very old issue because at this point there is no chance that I'm going to retroactively support Ruby 1.8.

**Comment by opello** [comment]
It's not like it was a huge lift but somewhere I can appreciate moving on from old versions.  :)
