### ISSUE TITLE
Drop OohEmbed support, support Noembed

### ISSUE THREAD

**Issue by evaryont** [ruby-oembed/ruby-oembed#32]
OohEmbed was shut down ([a while ago](http://blog.embed.ly/post/45150009135/oohembed), actually. Seems it was July 20th 2011).

However, since then [Noembed.com](http://noembed.com/) has come out, which seems to fill the same shoes.

**Comment by metavida** [comment]
Ok, with ruby-oembed 0.12.0 (released just now) while I didn't completely remove the `OEmbed::Providers::OohEmbed` class, I *did* 

1. Add support for the `OEmbed::Providers::Noembed` provider
2. [Update the README](https://github.com/ruby-oembed/ruby-oembed/blob/cd3f3531e3b0d1d0dec833af6f2b5142fc35be0f/README.md#fallback-providers) to OohEmbed, replacing it with mentions of Noembed.

@arnaud, while I don't dynamically load the list of providers for Noembed, I *did* use your code as the base of the `rake oembed:update_noembed` task I added.

With all that in mind, I'm gonna consider this issue closed. If you disagree, feel free to write back!
