### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by oyeanuj** [ruby-oembed/ruby-oembed#65]
Hi @metavida! Just came across the project, and it looks great!

Since the readme says the 1.0 is under works, I am wondering if I could get a sense of what are the big parts that you are thinking for the 1.0? And if you had a sense of how far out that might be?

Thank you for your work on this!

**Comment by metavida** [comment]
Thanks for your interest! The 1.0 is all about cleaning up & polishing. I'm removing a number of deprecated methods, removing a few built-in providers for services that have shut down, and introduced rubocop to help enforce consistent code style. 

You can read more about the upcoming changes that I've completed so far here: https://github.com/ruby-oembed/ruby-oembed/blob/128bac0eb21a34a068ba6bb18a515df6e631a0e8/CHANGELOG.rdoc

You can also [check out the diff](https://github.com/ruby-oembed/ruby-oembed/compare/rubocop). 

Timeline is trickier. I work in DevOps for an education company so the next month and a bit are insane as we work to keep up with beginning of school traffic, so I honestly have no clear idea of when inspiration & free time will line up for me to finish of the 1.0. 

So, if you just want to use this gem, go ahead and use the current version! It's stable & my company uses it in production. If you want to send a pull request, consider forking off the rubocop branch.

**Comment by simmerz** [comment]
@metavida is there any development intended on this gem or is it now unmaintained (in favour of something else, or lack of use?)

**Comment by metavida** [comment]
For fun I went back and looked at the diff with the `rubocop` branch today. There's a _lot_ of solid things in that branch _but/and_ there's basically zero chance of this gem getting its 1.0 release any time soon, so I'm gonna close this issue (Reasons: all of those changes are now 6 years old, and I'm not working on project that actually uses/needs this library anymore, and I'm not even writing ruby at work anymore).

> is there any development intended on this gem or is it now unmaintained

I don't have any plans to actively improve this gem but I'm _glad_ to keep reviewing & merging & releasing PRs submitted by the folks who still use the gem!
