### ISSUE TITLE
Add Speakerdeck support

### ISSUE THREAD

**Issue by camilleroux** [ruby-oembed/ruby-oembed#67]
Could you add Speakerdeck support ?

Supported URL schemes for Speaker Deck rich embed are:
http://speakerdeck.com/*/*
https://speakerdeck.com/*/*

**Comment by metavida** [comment]
Yeah, it looks Speakerdeck does offer documented support of oembed, so it should be easy to add an official provider in this gem. In the short term you can even dynamically register Speakerdeck in your list of supported proveders in your app. 

https://speakerdeck.com/faq#oembed

That said, my work is really hectic at the moment, which leaves very little time for work on side projects like this gem. I'll do my best to get this in, in a not toooo unreasonable amount of time, though.

**Comment by metavida** [comment]
I just release ruby-oembed 0.11.0 with an built-in Speaker Deck provider at `OEmbed::Providers::SpeakerDeck` and also available via `OEmbed::Providers.register_all`

Hope you're having a great weekend!
